language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
install:
  - yarn install
services:
  - postgresql

env:
  global:
    - NODE_ENV=test

before_script:
  - psql -c 'create database properties_test' -U postgres
  - psql -c "CREATE USER mwas WITH PASSWORD null;" -U postgres
  - yarn build
  - yarn add -g sequelize-cli
  - sequelize db:migrate
script:
  - yarn test
after_success:
  - yarn coverage
